#pragma once

// 리소스의 숫자 ID에 심볼 이름을 부여

#define IDI_KNOTENGINE 101
#define IDR_ENGINE_ICON_PNG 201
#define IDR_PRETENDARD_MEDIUM 202
#define IDR_PRETENDARD_SEMIBOLD 203
#define IDR_PRETENDARD_LICENSE 204
#define IDR_GEOMETRY_MESH_SHADER 205
#define IDR_GRID_SHADER 206
#define IDR_AXIS_SHADER 207
#define IDR_STATIC_MESH_SHADER 208
