#pragma once

#define IDI_KNOTENGINE 101
#define IDR_ENGINE_ICON_PNG 201
#define IDR_PRETENDARD_MEDIUM 202
#define IDR_PRETENDARD_SEMIBOLD 203
#define IDR_PRETENDARD_LICENSE 204
#define IDR_COMMON_SHADER 205
